# Generated by Django 4.1.6 on 2023-02-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets_booked',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_left',
            field=models.IntegerField(),
        ),
    ]
